name: GitHub Snake Game

on:
  # Schedule the workflow to run daily at midnight UTC
  schedule:
    - cron: "0 0 * * *"

  # Allow manual triggering of the workflow
  workflow_dispatch:

  # Trigger the workflow on pushes to the main branch
  push:
    branches:
      - main

permissions:   # 👈 eklenen kısım
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
