name: Generate GitHub Contributions Snake
on:
  schedule:
    # her 12 saatte bir çalışır
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate snake (SVG + dark mode SVG)
        uses: Platane/snk@v3
        with:
          github_user_name: senademirbas
          outputs: |
            output/github-contribution-grid-snake.svg
            output/github-contribution-grid-snake-dark.svg?palette=github-dark
