name: Generate GitHub Contributions Snake
on:
  schedule:
    # her 12 saatte bir (isteğe göre değiştir)
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write   # action'ın üretilen dosyayı repoya yazabilmesi için

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate snake (SVG + dark mode SVG)
        uses: Platane/snk@v3
        with:
          # read contributions for the owner of the repo; veya doğrudan kullanıcı ismi yaz
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            output/github-contribution-grid-snake.svg
            output/github-contribution-grid-snake-dark.svg?palette=github-dark
